#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 14
#define STATE_COUNT 149
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 59
#define ALIAS_COUNT 0
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 3
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 5
#define PRODUCTION_ID_COUNT 4

enum ts_symbol_identifiers {
  sym_identifier = 1,
  sym_string = 2,
  anon_sym_LT = 3,
  anon_sym_GT = 4,
  anon_sym_LT_SLASH = 5,
  anon_sym_SLASH_GT = 6,
  anon_sym_EQ = 7,
  sym_attribute_name = 8,
  sym_attribute_value = 9,
  anon_sym_SQUOTE = 10,
  aux_sym_quoted_attribute_value_token1 = 11,
  anon_sym_DQUOTE = 12,
  aux_sym_quoted_attribute_value_token2 = 13,
  anon_sym_LBRACE_LBRACE = 14,
  anon_sym_RBRACE_RBRACE = 15,
  anon_sym_LBRACE_PERCENT = 16,
  anon_sym_PERCENT_RBRACE = 17,
  anon_sym_block = 18,
  anon_sym_endblock = 19,
  anon_sym_include = 20,
  anon_sym_extends = 21,
  anon_sym_if = 22,
  anon_sym_else = 23,
  anon_sym_elif = 24,
  anon_sym_endif = 25,
  sym__expression_content = 26,
  sym__statement_content = 27,
  sym__html_comment = 28,
  sym_document = 29,
  sym__tag_name = 30,
  sym_content = 31,
  sym__node = 32,
  sym_element = 33,
  sym_start_tag = 34,
  sym_end_tag = 35,
  sym_self_closing_tag = 36,
  sym_html_comment = 37,
  sym_attribute = 38,
  sym_quoted_attribute_value = 39,
  sym_expression = 40,
  sym_start_expression = 41,
  sym_end_expression = 42,
  sym_statement = 43,
  sym_unpaired_statement = 44,
  sym_paired_statement = 45,
  sym_start_statement = 46,
  sym_end_statement = 47,
  sym_block_start_statement = 48,
  sym_block_end_statement = 49,
  sym_include_statement = 50,
  sym_extends_statement = 51,
  sym_if_statement = 52,
  sym_else_statement = 53,
  sym_elif_statement = 54,
  sym_endif_statement = 55,
  aux_sym_document_repeat1 = 56,
  aux_sym_element_repeat1 = 57,
  aux_sym_start_tag_repeat1 = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [sym_identifier] = "identifier",
  [sym_string] = "path",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "attribute_value",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "attribute_value",
  [anon_sym_LBRACE_LBRACE] = "{{",
  [anon_sym_RBRACE_RBRACE] = "}}",
  [anon_sym_LBRACE_PERCENT] = "{%",
  [anon_sym_PERCENT_RBRACE] = "%}",
  [anon_sym_block] = "tag_name",
  [anon_sym_endblock] = "tag_name",
  [anon_sym_include] = "tag_name",
  [anon_sym_extends] = "tag_name",
  [anon_sym_if] = "tag_name",
  [anon_sym_else] = "tag_name",
  [anon_sym_elif] = "tag_name",
  [anon_sym_endif] = "tag_name",
  [sym__expression_content] = "expression_content",
  [sym__statement_content] = "statement_content",
  [sym__html_comment] = "comment",
  [sym_document] = "document",
  [sym__tag_name] = "_tag_name",
  [sym_content] = "content",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_end_tag] = "end_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_html_comment] = "html_comment",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_expression] = "expression",
  [sym_start_expression] = "start_expression",
  [sym_end_expression] = "end_expression",
  [sym_statement] = "statement",
  [sym_unpaired_statement] = "unpaired_statement",
  [sym_paired_statement] = "paired_statement",
  [sym_start_statement] = "start_statement",
  [sym_end_statement] = "end_statement",
  [sym_block_start_statement] = "block_start_statement",
  [sym_block_end_statement] = "block_end_statement",
  [sym_include_statement] = "include_statement",
  [sym_extends_statement] = "extends_statement",
  [sym_if_statement] = "if_statement",
  [sym_else_statement] = "else_statement",
  [sym_elif_statement] = "elif_statement",
  [sym_endif_statement] = "endif_statement",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_element_repeat1] = "element_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [sym_identifier] = sym_identifier,
  [sym_string] = sym_string,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = sym_attribute_value,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = sym_attribute_value,
  [anon_sym_LBRACE_LBRACE] = anon_sym_LBRACE_LBRACE,
  [anon_sym_RBRACE_RBRACE] = anon_sym_RBRACE_RBRACE,
  [anon_sym_LBRACE_PERCENT] = anon_sym_LBRACE_PERCENT,
  [anon_sym_PERCENT_RBRACE] = anon_sym_PERCENT_RBRACE,
  [anon_sym_block] = anon_sym_block,
  [anon_sym_endblock] = anon_sym_block,
  [anon_sym_include] = anon_sym_block,
  [anon_sym_extends] = anon_sym_block,
  [anon_sym_if] = anon_sym_block,
  [anon_sym_else] = anon_sym_block,
  [anon_sym_elif] = anon_sym_block,
  [anon_sym_endif] = anon_sym_block,
  [sym__expression_content] = sym__expression_content,
  [sym__statement_content] = sym__statement_content,
  [sym__html_comment] = sym__html_comment,
  [sym_document] = sym_document,
  [sym__tag_name] = sym__tag_name,
  [sym_content] = sym_content,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_html_comment] = sym_html_comment,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_expression] = sym_expression,
  [sym_start_expression] = sym_start_expression,
  [sym_end_expression] = sym_end_expression,
  [sym_statement] = sym_statement,
  [sym_unpaired_statement] = sym_unpaired_statement,
  [sym_paired_statement] = sym_paired_statement,
  [sym_start_statement] = sym_start_statement,
  [sym_end_statement] = sym_end_statement,
  [sym_block_start_statement] = sym_block_start_statement,
  [sym_block_end_statement] = sym_block_end_statement,
  [sym_include_statement] = sym_include_statement,
  [sym_extends_statement] = sym_extends_statement,
  [sym_if_statement] = sym_if_statement,
  [sym_else_statement] = sym_else_statement,
  [sym_elif_statement] = sym_elif_statement,
  [sym_endif_statement] = sym_endif_statement,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_element_repeat1] = aux_sym_element_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [sym_identifier] = {
    .visible = true,
    .named = true,
  },
  [sym_string] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_LBRACE_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LBRACE_PERCENT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_PERCENT_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_endblock] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_extends] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_if] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_else] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_elif] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_endif] = {
    .visible = true,
    .named = true,
  },
  [sym__expression_content] = {
    .visible = true,
    .named = true,
  },
  [sym__statement_content] = {
    .visible = true,
    .named = true,
  },
  [sym__html_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__tag_name] = {
    .visible = false,
    .named = true,
  },
  [sym_content] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_html_comment] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_start_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_end_expression] = {
    .visible = true,
    .named = true,
  },
  [sym_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_unpaired_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_paired_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_start_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_end_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_start_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_include_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_extends_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_if_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_else_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_elif_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_endif_statement] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_element_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [0] = sym_content,
  },
  [2] = {
    [0] = sym__html_comment,
  },
  [3] = {
    [0] = anon_sym_block,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 3,
  [5] = 5,
  [6] = 5,
  [7] = 7,
  [8] = 8,
  [9] = 8,
  [10] = 2,
  [11] = 5,
  [12] = 7,
  [13] = 3,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 17,
  [18] = 18,
  [19] = 18,
  [20] = 16,
  [21] = 21,
  [22] = 21,
  [23] = 21,
  [24] = 24,
  [25] = 25,
  [26] = 26,
  [27] = 27,
  [28] = 28,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 32,
  [48] = 39,
  [49] = 37,
  [50] = 34,
  [51] = 33,
  [52] = 41,
  [53] = 36,
  [54] = 38,
  [55] = 24,
  [56] = 29,
  [57] = 40,
  [58] = 31,
  [59] = 43,
  [60] = 44,
  [61] = 45,
  [62] = 30,
  [63] = 28,
  [64] = 25,
  [65] = 26,
  [66] = 46,
  [67] = 35,
  [68] = 27,
  [69] = 42,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 25,
  [75] = 24,
  [76] = 76,
  [77] = 77,
  [78] = 28,
  [79] = 32,
  [80] = 35,
  [81] = 45,
  [82] = 82,
  [83] = 27,
  [84] = 29,
  [85] = 36,
  [86] = 38,
  [87] = 87,
  [88] = 26,
  [89] = 43,
  [90] = 44,
  [91] = 91,
  [92] = 92,
  [93] = 91,
  [94] = 91,
  [95] = 92,
  [96] = 96,
  [97] = 97,
  [98] = 98,
  [99] = 99,
  [100] = 96,
  [101] = 101,
  [102] = 102,
  [103] = 97,
  [104] = 102,
  [105] = 98,
  [106] = 102,
  [107] = 97,
  [108] = 108,
  [109] = 98,
  [110] = 108,
  [111] = 111,
  [112] = 112,
  [113] = 111,
  [114] = 114,
  [115] = 115,
  [116] = 116,
  [117] = 117,
  [118] = 118,
  [119] = 119,
  [120] = 112,
  [121] = 121,
  [122] = 122,
  [123] = 123,
  [124] = 114,
  [125] = 123,
  [126] = 112,
  [127] = 117,
  [128] = 118,
  [129] = 129,
  [130] = 122,
  [131] = 122,
  [132] = 111,
  [133] = 114,
  [134] = 134,
  [135] = 135,
  [136] = 116,
  [137] = 117,
  [138] = 134,
  [139] = 139,
  [140] = 140,
  [141] = 139,
  [142] = 129,
  [143] = 140,
  [144] = 118,
  [145] = 134,
  [146] = 139,
  [147] = 140,
  [148] = 129,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(38);
      ADVANCE_MAP(
        '"', 55,
        '%', 35,
        '\'', 52,
        '/', 8,
        '<', 43,
        '=', 47,
        '>', 44,
        'b', 25,
        'e', 26,
        'i', 19,
        '{', 4,
        '}', 36,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(0);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(55);
      if (lookahead == '\'') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(1);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(51);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(55);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0) ADVANCE(57);
      END_STATE();
    case 3:
      if (lookahead == '"') ADVANCE(41);
      if (lookahead != 0) ADVANCE(3);
      END_STATE();
    case 4:
      if (lookahead == '%') ADVANCE(61);
      if (lookahead == '{') ADVANCE(58);
      END_STATE();
    case 5:
      if (lookahead == '\'') ADVANCE(52);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0) ADVANCE(54);
      END_STATE();
    case 6:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '<') ADVANCE(42);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '{') ADVANCE(48);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(6);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 7:
      if (lookahead == '/') ADVANCE(8);
      if (lookahead == '=') ADVANCE(47);
      if (lookahead == '>') ADVANCE(44);
      if (lookahead == '{') ADVANCE(49);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(7);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 8:
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 9:
      if (lookahead == 'b') ADVANCE(28);
      if (lookahead == 'i') ADVANCE(21);
      END_STATE();
    case 10:
      if (lookahead == 'c') ADVANCE(23);
      END_STATE();
    case 11:
      if (lookahead == 'c') ADVANCE(27);
      END_STATE();
    case 12:
      if (lookahead == 'c') ADVANCE(24);
      END_STATE();
    case 13:
      if (lookahead == 'd') ADVANCE(9);
      END_STATE();
    case 14:
      if (lookahead == 'd') ADVANCE(32);
      END_STATE();
    case 15:
      if (lookahead == 'd') ADVANCE(18);
      END_STATE();
    case 16:
      if (lookahead == 'e') ADVANCE(69);
      END_STATE();
    case 17:
      if (lookahead == 'e') ADVANCE(29);
      END_STATE();
    case 18:
      if (lookahead == 'e') ADVANCE(66);
      END_STATE();
    case 19:
      if (lookahead == 'f') ADVANCE(68);
      if (lookahead == 'n') ADVANCE(11);
      END_STATE();
    case 20:
      if (lookahead == 'f') ADVANCE(70);
      END_STATE();
    case 21:
      if (lookahead == 'f') ADVANCE(71);
      END_STATE();
    case 22:
      if (lookahead == 'i') ADVANCE(20);
      if (lookahead == 's') ADVANCE(16);
      END_STATE();
    case 23:
      if (lookahead == 'k') ADVANCE(64);
      END_STATE();
    case 24:
      if (lookahead == 'k') ADVANCE(65);
      END_STATE();
    case 25:
      if (lookahead == 'l') ADVANCE(30);
      END_STATE();
    case 26:
      if (lookahead == 'l') ADVANCE(22);
      if (lookahead == 'n') ADVANCE(13);
      if (lookahead == 'x') ADVANCE(33);
      END_STATE();
    case 27:
      if (lookahead == 'l') ADVANCE(34);
      END_STATE();
    case 28:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 29:
      if (lookahead == 'n') ADVANCE(14);
      END_STATE();
    case 30:
      if (lookahead == 'o') ADVANCE(10);
      END_STATE();
    case 31:
      if (lookahead == 'o') ADVANCE(12);
      END_STATE();
    case 32:
      if (lookahead == 's') ADVANCE(67);
      END_STATE();
    case 33:
      if (lookahead == 't') ADVANCE(17);
      END_STATE();
    case 34:
      if (lookahead == 'u') ADVANCE(15);
      END_STATE();
    case 35:
      if (lookahead == '}') ADVANCE(63);
      END_STATE();
    case 36:
      if (lookahead == '}') ADVANCE(60);
      END_STATE();
    case 37:
      if (eof) ADVANCE(38);
      if (lookahead == '"') ADVANCE(3);
      if (lookahead == '<') ADVANCE(43);
      if (lookahead == '{') ADVANCE(4);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 38:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(39);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(sym_identifier);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(40);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '/' || '9' < lookahead) &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(sym_string);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_LT);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(45);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '%') ADVANCE(62);
      if (lookahead == '{') ADVANCE(59);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '%') ADVANCE(62);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(51);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(53);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(54);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '\'') ADVANCE(54);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(56);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"') ADVANCE(57);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(anon_sym_LBRACE_LBRACE);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(anon_sym_RBRACE_RBRACE);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(anon_sym_LBRACE_PERCENT);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          lookahead != '/' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(anon_sym_PERCENT_RBRACE);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(anon_sym_endblock);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(anon_sym_extends);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(anon_sym_if);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(anon_sym_else);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(anon_sym_elif);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(anon_sym_endif);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 37},
  [2] = {.lex_state = 6},
  [3] = {.lex_state = 6},
  [4] = {.lex_state = 6},
  [5] = {.lex_state = 6},
  [6] = {.lex_state = 6},
  [7] = {.lex_state = 37},
  [8] = {.lex_state = 37},
  [9] = {.lex_state = 37},
  [10] = {.lex_state = 37},
  [11] = {.lex_state = 37},
  [12] = {.lex_state = 37},
  [13] = {.lex_state = 37},
  [14] = {.lex_state = 37},
  [15] = {.lex_state = 37},
  [16] = {.lex_state = 7},
  [17] = {.lex_state = 7},
  [18] = {.lex_state = 7},
  [19] = {.lex_state = 7},
  [20] = {.lex_state = 7},
  [21] = {.lex_state = 0},
  [22] = {.lex_state = 0},
  [23] = {.lex_state = 0},
  [24] = {.lex_state = 6},
  [25] = {.lex_state = 6},
  [26] = {.lex_state = 6},
  [27] = {.lex_state = 6},
  [28] = {.lex_state = 6},
  [29] = {.lex_state = 6},
  [30] = {.lex_state = 6},
  [31] = {.lex_state = 6},
  [32] = {.lex_state = 6},
  [33] = {.lex_state = 6},
  [34] = {.lex_state = 6},
  [35] = {.lex_state = 6},
  [36] = {.lex_state = 6},
  [37] = {.lex_state = 6},
  [38] = {.lex_state = 6},
  [39] = {.lex_state = 6},
  [40] = {.lex_state = 6},
  [41] = {.lex_state = 6},
  [42] = {.lex_state = 6},
  [43] = {.lex_state = 6},
  [44] = {.lex_state = 6},
  [45] = {.lex_state = 6},
  [46] = {.lex_state = 6},
  [47] = {.lex_state = 37},
  [48] = {.lex_state = 37},
  [49] = {.lex_state = 37},
  [50] = {.lex_state = 37},
  [51] = {.lex_state = 37},
  [52] = {.lex_state = 37},
  [53] = {.lex_state = 37},
  [54] = {.lex_state = 37},
  [55] = {.lex_state = 37},
  [56] = {.lex_state = 37},
  [57] = {.lex_state = 37},
  [58] = {.lex_state = 37},
  [59] = {.lex_state = 37},
  [60] = {.lex_state = 37},
  [61] = {.lex_state = 37},
  [62] = {.lex_state = 37},
  [63] = {.lex_state = 37},
  [64] = {.lex_state = 37},
  [65] = {.lex_state = 37},
  [66] = {.lex_state = 37},
  [67] = {.lex_state = 37},
  [68] = {.lex_state = 37},
  [69] = {.lex_state = 37},
  [70] = {.lex_state = 7},
  [71] = {.lex_state = 37},
  [72] = {.lex_state = 37},
  [73] = {.lex_state = 7},
  [74] = {.lex_state = 7},
  [75] = {.lex_state = 7},
  [76] = {.lex_state = 7},
  [77] = {.lex_state = 7},
  [78] = {.lex_state = 7},
  [79] = {.lex_state = 7},
  [80] = {.lex_state = 7},
  [81] = {.lex_state = 7},
  [82] = {.lex_state = 7},
  [83] = {.lex_state = 7},
  [84] = {.lex_state = 7},
  [85] = {.lex_state = 7},
  [86] = {.lex_state = 7},
  [87] = {.lex_state = 1},
  [88] = {.lex_state = 7},
  [89] = {.lex_state = 7},
  [90] = {.lex_state = 7},
  [91] = {.lex_state = 0},
  [92] = {.lex_state = 37, .external_lex_state = 2},
  [93] = {.lex_state = 0},
  [94] = {.lex_state = 0},
  [95] = {.lex_state = 37, .external_lex_state = 2},
  [96] = {.lex_state = 37},
  [97] = {.lex_state = 0},
  [98] = {.lex_state = 0},
  [99] = {.lex_state = 5},
  [100] = {.lex_state = 37},
  [101] = {.lex_state = 2},
  [102] = {.lex_state = 0},
  [103] = {.lex_state = 0},
  [104] = {.lex_state = 0},
  [105] = {.lex_state = 0},
  [106] = {.lex_state = 0},
  [107] = {.lex_state = 0},
  [108] = {.lex_state = 0},
  [109] = {.lex_state = 0},
  [110] = {.lex_state = 0},
  [111] = {.lex_state = 0},
  [112] = {.lex_state = 0, .external_lex_state = 3},
  [113] = {.lex_state = 0},
  [114] = {.lex_state = 0},
  [115] = {.lex_state = 0},
  [116] = {.lex_state = 0, .external_lex_state = 4},
  [117] = {.lex_state = 0},
  [118] = {.lex_state = 0},
  [119] = {.lex_state = 0},
  [120] = {.lex_state = 0, .external_lex_state = 3},
  [121] = {.lex_state = 0},
  [122] = {.lex_state = 0},
  [123] = {.lex_state = 0},
  [124] = {.lex_state = 0},
  [125] = {.lex_state = 0},
  [126] = {.lex_state = 0, .external_lex_state = 3},
  [127] = {.lex_state = 0},
  [128] = {.lex_state = 0},
  [129] = {.lex_state = 0, .external_lex_state = 3},
  [130] = {.lex_state = 0},
  [131] = {.lex_state = 0},
  [132] = {.lex_state = 0},
  [133] = {.lex_state = 0},
  [134] = {.lex_state = 37},
  [135] = {.lex_state = 0, .external_lex_state = 4},
  [136] = {.lex_state = 0, .external_lex_state = 4},
  [137] = {.lex_state = 0},
  [138] = {.lex_state = 37},
  [139] = {.lex_state = 37},
  [140] = {.lex_state = 37},
  [141] = {.lex_state = 37},
  [142] = {.lex_state = 0, .external_lex_state = 3},
  [143] = {.lex_state = 37},
  [144] = {.lex_state = 0},
  [145] = {.lex_state = 37},
  [146] = {.lex_state = 37},
  [147] = {.lex_state = 37},
  [148] = {.lex_state = 0, .external_lex_state = 3},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [0] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE_RBRACE] = ACTIONS(1),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(1),
    [anon_sym_PERCENT_RBRACE] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_endblock] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [anon_sym_extends] = ACTIONS(1),
    [anon_sym_if] = ACTIONS(1),
    [anon_sym_else] = ACTIONS(1),
    [anon_sym_elif] = ACTIONS(1),
    [anon_sym_endif] = ACTIONS(1),
    [sym__expression_content] = ACTIONS(1),
    [sym__statement_content] = ACTIONS(1),
    [sym__html_comment] = ACTIONS(1),
  },
  [1] = {
    [sym_document] = STATE(121),
    [sym_content] = STATE(14),
    [sym__node] = STATE(14),
    [sym_element] = STATE(14),
    [sym_start_tag] = STATE(8),
    [sym_self_closing_tag] = STATE(66),
    [sym_html_comment] = STATE(14),
    [sym_expression] = STATE(14),
    [sym_start_expression] = STATE(116),
    [sym_statement] = STATE(14),
    [sym_unpaired_statement] = STATE(68),
    [sym_paired_statement] = STATE(68),
    [sym_start_statement] = STATE(94),
    [sym_block_start_statement] = STATE(65),
    [sym_block_end_statement] = STATE(64),
    [sym_include_statement] = STATE(56),
    [sym_extends_statement] = STATE(56),
    [sym_if_statement] = STATE(55),
    [sym_else_statement] = STATE(55),
    [sym_elif_statement] = STATE(55),
    [sym_endif_statement] = STATE(55),
    [aux_sym_document_repeat1] = STATE(14),
    [ts_builtin_sym_end] = ACTIONS(3),
    [sym_identifier] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [anon_sym_LBRACE_LBRACE] = ACTIONS(9),
    [anon_sym_LBRACE_PERCENT] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 16,
    ACTIONS(13), 1,
      sym_identifier,
    ACTIONS(16), 1,
      anon_sym_LT,
    ACTIONS(21), 1,
      sym_attribute_name,
    ACTIONS(23), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(26), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(9), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_block_end_statement,
    STATE(26), 1,
      sym_block_start_statement,
    STATE(46), 1,
      sym_self_closing_tag,
    STATE(93), 1,
      sym_start_statement,
    STATE(136), 1,
      sym_start_expression,
    ACTIONS(19), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(27), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(29), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(24), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(2), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [61] = 12,
    STATE(9), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_block_end_statement,
    STATE(26), 1,
      sym_block_start_statement,
    STATE(46), 1,
      sym_self_closing_tag,
    STATE(93), 1,
      sym_start_statement,
    STATE(136), 1,
      sym_start_expression,
    STATE(27), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(29), 2,
      sym_include_statement,
      sym_extends_statement,
    ACTIONS(31), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(29), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
    STATE(24), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(2), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [114] = 15,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(9), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_block_end_statement,
    STATE(26), 1,
      sym_block_start_statement,
    STATE(46), 1,
      sym_self_closing_tag,
    STATE(93), 1,
      sym_start_statement,
    STATE(136), 1,
      sym_start_expression,
    ACTIONS(29), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(31), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(27), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(29), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(24), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(2), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [173] = 15,
    ACTIONS(33), 1,
      sym_identifier,
    ACTIONS(35), 1,
      anon_sym_LT,
    ACTIONS(37), 1,
      anon_sym_LBRACE_LBRACE,
    STATE(9), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_block_end_statement,
    STATE(26), 1,
      sym_block_start_statement,
    STATE(46), 1,
      sym_self_closing_tag,
    STATE(93), 1,
      sym_start_statement,
    STATE(136), 1,
      sym_start_expression,
    ACTIONS(39), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(41), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    STATE(27), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(29), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(24), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(4), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [232] = 12,
    STATE(9), 1,
      sym_start_tag,
    STATE(25), 1,
      sym_block_end_statement,
    STATE(26), 1,
      sym_block_start_statement,
    STATE(46), 1,
      sym_self_closing_tag,
    STATE(93), 1,
      sym_start_statement,
    STATE(136), 1,
      sym_start_expression,
    STATE(27), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(29), 2,
      sym_include_statement,
      sym_extends_statement,
    ACTIONS(39), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(41), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
    STATE(24), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(3), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [285] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_start_tag,
    STATE(49), 1,
      sym_end_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(10), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [345] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(45), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_start_tag,
    STATE(57), 1,
      sym_end_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(7), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [405] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_start_tag,
    STATE(40), 1,
      sym_end_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(12), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [465] = 15,
    ACTIONS(49), 1,
      sym_identifier,
    ACTIONS(52), 1,
      anon_sym_LT,
    ACTIONS(55), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(58), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(8), 1,
      sym_start_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    ACTIONS(19), 2,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(10), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [523] = 12,
    ACTIONS(41), 1,
      anon_sym_LT,
    STATE(8), 1,
      sym_start_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    ACTIONS(39), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
    STATE(13), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [575] = 16,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(43), 1,
      anon_sym_LT,
    ACTIONS(47), 1,
      anon_sym_LT_SLASH,
    STATE(8), 1,
      sym_start_tag,
    STATE(37), 1,
      sym_end_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(10), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [635] = 12,
    ACTIONS(29), 1,
      anon_sym_LT,
    STATE(8), 1,
      sym_start_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    ACTIONS(31), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
    STATE(10), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_element_repeat1,
  [687] = 15,
    ACTIONS(5), 1,
      sym_identifier,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(9), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(11), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(61), 1,
      ts_builtin_sym_end,
    STATE(8), 1,
      sym_start_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(15), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_document_repeat1,
  [744] = 15,
    ACTIONS(63), 1,
      ts_builtin_sym_end,
    ACTIONS(65), 1,
      sym_identifier,
    ACTIONS(68), 1,
      anon_sym_LT,
    ACTIONS(71), 1,
      anon_sym_LBRACE_LBRACE,
    ACTIONS(74), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(8), 1,
      sym_start_tag,
    STATE(64), 1,
      sym_block_end_statement,
    STATE(65), 1,
      sym_block_start_statement,
    STATE(66), 1,
      sym_self_closing_tag,
    STATE(94), 1,
      sym_start_statement,
    STATE(116), 1,
      sym_start_expression,
    STATE(56), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(68), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(55), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
    STATE(15), 7,
      sym_content,
      sym__node,
      sym_element,
      sym_html_comment,
      sym_expression,
      sym_statement,
      aux_sym_document_repeat1,
  [801] = 11,
    ACTIONS(77), 1,
      anon_sym_GT,
    ACTIONS(79), 1,
      anon_sym_SLASH_GT,
    ACTIONS(81), 1,
      sym_attribute_name,
    ACTIONS(83), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(74), 1,
      sym_block_end_statement,
    STATE(88), 1,
      sym_block_start_statement,
    STATE(91), 1,
      sym_start_statement,
    STATE(83), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(84), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(19), 3,
      sym_attribute,
      sym_statement,
      aux_sym_start_tag_repeat1,
    STATE(75), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
  [842] = 10,
    ACTIONS(87), 1,
      sym_attribute_name,
    ACTIONS(90), 1,
      anon_sym_LBRACE_PERCENT,
    STATE(74), 1,
      sym_block_end_statement,
    STATE(88), 1,
      sym_block_start_statement,
    STATE(91), 1,
      sym_start_statement,
    ACTIONS(85), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(83), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(84), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(17), 3,
      sym_attribute,
      sym_statement,
      aux_sym_start_tag_repeat1,
    STATE(75), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
  [881] = 11,
    ACTIONS(81), 1,
      sym_attribute_name,
    ACTIONS(83), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(93), 1,
      anon_sym_GT,
    ACTIONS(95), 1,
      anon_sym_SLASH_GT,
    STATE(74), 1,
      sym_block_end_statement,
    STATE(88), 1,
      sym_block_start_statement,
    STATE(91), 1,
      sym_start_statement,
    STATE(83), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(84), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(17), 3,
      sym_attribute,
      sym_statement,
      aux_sym_start_tag_repeat1,
    STATE(75), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
  [922] = 11,
    ACTIONS(81), 1,
      sym_attribute_name,
    ACTIONS(83), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(93), 1,
      anon_sym_GT,
    ACTIONS(97), 1,
      anon_sym_SLASH_GT,
    STATE(74), 1,
      sym_block_end_statement,
    STATE(88), 1,
      sym_block_start_statement,
    STATE(91), 1,
      sym_start_statement,
    STATE(83), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(84), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(17), 3,
      sym_attribute,
      sym_statement,
      aux_sym_start_tag_repeat1,
    STATE(75), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
  [963] = 11,
    ACTIONS(77), 1,
      anon_sym_GT,
    ACTIONS(81), 1,
      sym_attribute_name,
    ACTIONS(83), 1,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(99), 1,
      anon_sym_SLASH_GT,
    STATE(74), 1,
      sym_block_end_statement,
    STATE(88), 1,
      sym_block_start_statement,
    STATE(91), 1,
      sym_start_statement,
    STATE(83), 2,
      sym_unpaired_statement,
      sym_paired_statement,
    STATE(84), 2,
      sym_include_statement,
      sym_extends_statement,
    STATE(18), 3,
      sym_attribute,
      sym_statement,
      aux_sym_start_tag_repeat1,
    STATE(75), 4,
      sym_if_statement,
      sym_else_statement,
      sym_elif_statement,
      sym_endif_statement,
  [1004] = 6,
    ACTIONS(101), 1,
      anon_sym_block,
    ACTIONS(103), 1,
      anon_sym_endblock,
    ACTIONS(105), 1,
      anon_sym_include,
    ACTIONS(107), 1,
      anon_sym_extends,
    ACTIONS(111), 1,
      anon_sym_endif,
    ACTIONS(109), 3,
      anon_sym_if,
      anon_sym_else,
      anon_sym_elif,
  [1025] = 6,
    ACTIONS(113), 1,
      anon_sym_block,
    ACTIONS(115), 1,
      anon_sym_endblock,
    ACTIONS(117), 1,
      anon_sym_include,
    ACTIONS(119), 1,
      anon_sym_extends,
    ACTIONS(121), 1,
      anon_sym_endif,
    ACTIONS(109), 3,
      anon_sym_if,
      anon_sym_else,
      anon_sym_elif,
  [1046] = 6,
    ACTIONS(123), 1,
      anon_sym_block,
    ACTIONS(125), 1,
      anon_sym_endblock,
    ACTIONS(127), 1,
      anon_sym_include,
    ACTIONS(129), 1,
      anon_sym_extends,
    ACTIONS(131), 1,
      anon_sym_endif,
    ACTIONS(109), 3,
      anon_sym_if,
      anon_sym_else,
      anon_sym_elif,
  [1067] = 2,
    ACTIONS(135), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(133), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1079] = 2,
    ACTIONS(135), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(133), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1091] = 2,
    ACTIONS(135), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(133), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1103] = 2,
    ACTIONS(139), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(137), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1115] = 2,
    ACTIONS(143), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(141), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1127] = 2,
    ACTIONS(147), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(145), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1139] = 2,
    ACTIONS(151), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(149), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1151] = 2,
    ACTIONS(155), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(153), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1163] = 2,
    ACTIONS(159), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(157), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1175] = 2,
    ACTIONS(163), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(161), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1187] = 2,
    ACTIONS(167), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(165), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1199] = 2,
    ACTIONS(171), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(169), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1211] = 2,
    ACTIONS(175), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(173), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1223] = 2,
    ACTIONS(179), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(177), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1235] = 2,
    ACTIONS(183), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(181), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1247] = 2,
    ACTIONS(187), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(185), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1259] = 2,
    ACTIONS(191), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(189), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1271] = 2,
    ACTIONS(195), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(193), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1283] = 2,
    ACTIONS(199), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(197), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1295] = 2,
    ACTIONS(203), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(201), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1307] = 2,
    ACTIONS(207), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(205), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1319] = 2,
    ACTIONS(211), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(209), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1331] = 2,
    ACTIONS(215), 3,
      anon_sym_LT,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(213), 4,
      sym_identifier,
      sym_attribute_name,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1343] = 2,
    ACTIONS(157), 1,
      anon_sym_LT,
    ACTIONS(159), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1354] = 2,
    ACTIONS(185), 1,
      anon_sym_LT,
    ACTIONS(187), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1365] = 2,
    ACTIONS(177), 1,
      anon_sym_LT,
    ACTIONS(179), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1376] = 2,
    ACTIONS(165), 1,
      anon_sym_LT,
    ACTIONS(167), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1387] = 2,
    ACTIONS(161), 1,
      anon_sym_LT,
    ACTIONS(163), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1398] = 2,
    ACTIONS(193), 1,
      anon_sym_LT,
    ACTIONS(195), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1409] = 2,
    ACTIONS(173), 1,
      anon_sym_LT,
    ACTIONS(175), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1420] = 2,
    ACTIONS(181), 1,
      anon_sym_LT,
    ACTIONS(183), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1431] = 2,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1442] = 2,
    ACTIONS(145), 1,
      anon_sym_LT,
    ACTIONS(147), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1453] = 2,
    ACTIONS(189), 1,
      anon_sym_LT,
    ACTIONS(191), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1464] = 2,
    ACTIONS(153), 1,
      anon_sym_LT,
    ACTIONS(155), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1475] = 2,
    ACTIONS(201), 1,
      anon_sym_LT,
    ACTIONS(203), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1486] = 2,
    ACTIONS(205), 1,
      anon_sym_LT,
    ACTIONS(207), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1497] = 2,
    ACTIONS(209), 1,
      anon_sym_LT,
    ACTIONS(211), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1508] = 2,
    ACTIONS(149), 1,
      anon_sym_LT,
    ACTIONS(151), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1519] = 2,
    ACTIONS(141), 1,
      anon_sym_LT,
    ACTIONS(143), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1530] = 2,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1541] = 2,
    ACTIONS(133), 1,
      anon_sym_LT,
    ACTIONS(135), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1552] = 2,
    ACTIONS(213), 1,
      anon_sym_LT,
    ACTIONS(215), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1563] = 2,
    ACTIONS(169), 1,
      anon_sym_LT,
    ACTIONS(171), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1574] = 2,
    ACTIONS(137), 1,
      anon_sym_LT,
    ACTIONS(139), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1585] = 2,
    ACTIONS(197), 1,
      anon_sym_LT,
    ACTIONS(199), 5,
      ts_builtin_sym_end,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1596] = 3,
    ACTIONS(219), 1,
      anon_sym_EQ,
    ACTIONS(217), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(221), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
  [1608] = 2,
    ACTIONS(225), 1,
      anon_sym_LT,
    ACTIONS(223), 4,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1618] = 2,
    ACTIONS(229), 1,
      anon_sym_LT,
    ACTIONS(227), 4,
      sym_identifier,
      anon_sym_LT_SLASH,
      anon_sym_LBRACE_LBRACE,
      anon_sym_LBRACE_PERCENT,
  [1628] = 2,
    ACTIONS(231), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(233), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
  [1637] = 2,
    ACTIONS(133), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1646] = 2,
    ACTIONS(133), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1655] = 2,
    ACTIONS(235), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(237), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
  [1664] = 2,
    ACTIONS(239), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(241), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
  [1673] = 2,
    ACTIONS(141), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(143), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1682] = 2,
    ACTIONS(157), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(159), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1691] = 2,
    ACTIONS(169), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(171), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1700] = 2,
    ACTIONS(209), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(211), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1709] = 2,
    ACTIONS(243), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    ACTIONS(245), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
  [1718] = 2,
    ACTIONS(137), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(139), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1727] = 2,
    ACTIONS(145), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(147), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1736] = 2,
    ACTIONS(173), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(175), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1745] = 2,
    ACTIONS(181), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(183), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1754] = 4,
    ACTIONS(247), 1,
      sym_attribute_value,
    ACTIONS(249), 1,
      anon_sym_SQUOTE,
    ACTIONS(251), 1,
      anon_sym_DQUOTE,
    STATE(73), 1,
      sym_quoted_attribute_value,
  [1767] = 2,
    ACTIONS(133), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(135), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1776] = 2,
    ACTIONS(201), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(203), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1785] = 2,
    ACTIONS(205), 2,
      sym_attribute_name,
      anon_sym_LBRACE_PERCENT,
    ACTIONS(207), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
  [1794] = 3,
    ACTIONS(253), 1,
      anon_sym_if,
    ACTIONS(255), 1,
      anon_sym_else,
    ACTIONS(257), 1,
      anon_sym_elif,
  [1804] = 3,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(261), 1,
      sym__html_comment,
    STATE(20), 1,
      sym__tag_name,
  [1814] = 3,
    ACTIONS(263), 1,
      anon_sym_if,
    ACTIONS(265), 1,
      anon_sym_else,
    ACTIONS(267), 1,
      anon_sym_elif,
  [1824] = 3,
    ACTIONS(269), 1,
      anon_sym_if,
    ACTIONS(271), 1,
      anon_sym_else,
    ACTIONS(273), 1,
      anon_sym_elif,
  [1834] = 3,
    ACTIONS(259), 1,
      sym_identifier,
    ACTIONS(275), 1,
      sym__html_comment,
    STATE(16), 1,
      sym__tag_name,
  [1844] = 2,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(123), 1,
      sym__tag_name,
  [1851] = 2,
    ACTIONS(277), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(86), 1,
      sym_end_statement,
  [1858] = 2,
    ACTIONS(279), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(63), 1,
      sym_end_statement,
  [1865] = 2,
    ACTIONS(281), 1,
      anon_sym_SQUOTE,
    ACTIONS(283), 1,
      aux_sym_quoted_attribute_value_token1,
  [1872] = 2,
    ACTIONS(259), 1,
      sym_identifier,
    STATE(125), 1,
      sym__tag_name,
  [1879] = 2,
    ACTIONS(281), 1,
      anon_sym_DQUOTE,
    ACTIONS(285), 1,
      aux_sym_quoted_attribute_value_token2,
  [1886] = 2,
    ACTIONS(287), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(6), 1,
      sym_end_statement,
  [1893] = 2,
    ACTIONS(287), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(38), 1,
      sym_end_statement,
  [1900] = 2,
    ACTIONS(279), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(11), 1,
      sym_end_statement,
  [1907] = 2,
    ACTIONS(287), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(28), 1,
      sym_end_statement,
  [1914] = 2,
    ACTIONS(287), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(5), 1,
      sym_end_statement,
  [1921] = 2,
    ACTIONS(279), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(54), 1,
      sym_end_statement,
  [1928] = 2,
    ACTIONS(289), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(51), 1,
      sym_end_expression,
  [1935] = 2,
    ACTIONS(277), 1,
      anon_sym_PERCENT_RBRACE,
    STATE(78), 1,
      sym_end_statement,
  [1942] = 2,
    ACTIONS(291), 1,
      anon_sym_RBRACE_RBRACE,
    STATE(33), 1,
      sym_end_expression,
  [1949] = 1,
    ACTIONS(293), 1,
      anon_sym_PERCENT_RBRACE,
  [1953] = 1,
    ACTIONS(295), 1,
      sym__statement_content,
  [1957] = 1,
    ACTIONS(297), 1,
      anon_sym_PERCENT_RBRACE,
  [1961] = 1,
    ACTIONS(299), 1,
      anon_sym_PERCENT_RBRACE,
  [1965] = 1,
    ACTIONS(301), 1,
      anon_sym_DQUOTE,
  [1969] = 1,
    ACTIONS(303), 1,
      sym__expression_content,
  [1973] = 1,
    ACTIONS(305), 1,
      anon_sym_PERCENT_RBRACE,
  [1977] = 1,
    ACTIONS(307), 1,
      anon_sym_PERCENT_RBRACE,
  [1981] = 1,
    ACTIONS(301), 1,
      anon_sym_SQUOTE,
  [1985] = 1,
    ACTIONS(309), 1,
      sym__statement_content,
  [1989] = 1,
    ACTIONS(311), 1,
      ts_builtin_sym_end,
  [1993] = 1,
    ACTIONS(313), 1,
      anon_sym_PERCENT_RBRACE,
  [1997] = 1,
    ACTIONS(315), 1,
      anon_sym_GT,
  [2001] = 1,
    ACTIONS(317), 1,
      anon_sym_PERCENT_RBRACE,
  [2005] = 1,
    ACTIONS(319), 1,
      anon_sym_GT,
  [2009] = 1,
    ACTIONS(321), 1,
      sym__statement_content,
  [2013] = 1,
    ACTIONS(323), 1,
      anon_sym_PERCENT_RBRACE,
  [2017] = 1,
    ACTIONS(325), 1,
      anon_sym_PERCENT_RBRACE,
  [2021] = 1,
    ACTIONS(327), 1,
      sym__statement_content,
  [2025] = 1,
    ACTIONS(329), 1,
      anon_sym_PERCENT_RBRACE,
  [2029] = 1,
    ACTIONS(331), 1,
      anon_sym_PERCENT_RBRACE,
  [2033] = 1,
    ACTIONS(333), 1,
      anon_sym_PERCENT_RBRACE,
  [2037] = 1,
    ACTIONS(335), 1,
      anon_sym_PERCENT_RBRACE,
  [2041] = 1,
    ACTIONS(337), 1,
      sym_identifier,
  [2045] = 1,
    ACTIONS(339), 1,
      sym__expression_content,
  [2049] = 1,
    ACTIONS(341), 1,
      sym__expression_content,
  [2053] = 1,
    ACTIONS(343), 1,
      anon_sym_PERCENT_RBRACE,
  [2057] = 1,
    ACTIONS(345), 1,
      sym_identifier,
  [2061] = 1,
    ACTIONS(347), 1,
      sym_string,
  [2065] = 1,
    ACTIONS(349), 1,
      sym_string,
  [2069] = 1,
    ACTIONS(351), 1,
      sym_string,
  [2073] = 1,
    ACTIONS(353), 1,
      sym__statement_content,
  [2077] = 1,
    ACTIONS(355), 1,
      sym_string,
  [2081] = 1,
    ACTIONS(357), 1,
      anon_sym_PERCENT_RBRACE,
  [2085] = 1,
    ACTIONS(359), 1,
      sym_identifier,
  [2089] = 1,
    ACTIONS(361), 1,
      sym_string,
  [2093] = 1,
    ACTIONS(363), 1,
      sym_string,
  [2097] = 1,
    ACTIONS(365), 1,
      sym__statement_content,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 61,
  [SMALL_STATE(4)] = 114,
  [SMALL_STATE(5)] = 173,
  [SMALL_STATE(6)] = 232,
  [SMALL_STATE(7)] = 285,
  [SMALL_STATE(8)] = 345,
  [SMALL_STATE(9)] = 405,
  [SMALL_STATE(10)] = 465,
  [SMALL_STATE(11)] = 523,
  [SMALL_STATE(12)] = 575,
  [SMALL_STATE(13)] = 635,
  [SMALL_STATE(14)] = 687,
  [SMALL_STATE(15)] = 744,
  [SMALL_STATE(16)] = 801,
  [SMALL_STATE(17)] = 842,
  [SMALL_STATE(18)] = 881,
  [SMALL_STATE(19)] = 922,
  [SMALL_STATE(20)] = 963,
  [SMALL_STATE(21)] = 1004,
  [SMALL_STATE(22)] = 1025,
  [SMALL_STATE(23)] = 1046,
  [SMALL_STATE(24)] = 1067,
  [SMALL_STATE(25)] = 1079,
  [SMALL_STATE(26)] = 1091,
  [SMALL_STATE(27)] = 1103,
  [SMALL_STATE(28)] = 1115,
  [SMALL_STATE(29)] = 1127,
  [SMALL_STATE(30)] = 1139,
  [SMALL_STATE(31)] = 1151,
  [SMALL_STATE(32)] = 1163,
  [SMALL_STATE(33)] = 1175,
  [SMALL_STATE(34)] = 1187,
  [SMALL_STATE(35)] = 1199,
  [SMALL_STATE(36)] = 1211,
  [SMALL_STATE(37)] = 1223,
  [SMALL_STATE(38)] = 1235,
  [SMALL_STATE(39)] = 1247,
  [SMALL_STATE(40)] = 1259,
  [SMALL_STATE(41)] = 1271,
  [SMALL_STATE(42)] = 1283,
  [SMALL_STATE(43)] = 1295,
  [SMALL_STATE(44)] = 1307,
  [SMALL_STATE(45)] = 1319,
  [SMALL_STATE(46)] = 1331,
  [SMALL_STATE(47)] = 1343,
  [SMALL_STATE(48)] = 1354,
  [SMALL_STATE(49)] = 1365,
  [SMALL_STATE(50)] = 1376,
  [SMALL_STATE(51)] = 1387,
  [SMALL_STATE(52)] = 1398,
  [SMALL_STATE(53)] = 1409,
  [SMALL_STATE(54)] = 1420,
  [SMALL_STATE(55)] = 1431,
  [SMALL_STATE(56)] = 1442,
  [SMALL_STATE(57)] = 1453,
  [SMALL_STATE(58)] = 1464,
  [SMALL_STATE(59)] = 1475,
  [SMALL_STATE(60)] = 1486,
  [SMALL_STATE(61)] = 1497,
  [SMALL_STATE(62)] = 1508,
  [SMALL_STATE(63)] = 1519,
  [SMALL_STATE(64)] = 1530,
  [SMALL_STATE(65)] = 1541,
  [SMALL_STATE(66)] = 1552,
  [SMALL_STATE(67)] = 1563,
  [SMALL_STATE(68)] = 1574,
  [SMALL_STATE(69)] = 1585,
  [SMALL_STATE(70)] = 1596,
  [SMALL_STATE(71)] = 1608,
  [SMALL_STATE(72)] = 1618,
  [SMALL_STATE(73)] = 1628,
  [SMALL_STATE(74)] = 1637,
  [SMALL_STATE(75)] = 1646,
  [SMALL_STATE(76)] = 1655,
  [SMALL_STATE(77)] = 1664,
  [SMALL_STATE(78)] = 1673,
  [SMALL_STATE(79)] = 1682,
  [SMALL_STATE(80)] = 1691,
  [SMALL_STATE(81)] = 1700,
  [SMALL_STATE(82)] = 1709,
  [SMALL_STATE(83)] = 1718,
  [SMALL_STATE(84)] = 1727,
  [SMALL_STATE(85)] = 1736,
  [SMALL_STATE(86)] = 1745,
  [SMALL_STATE(87)] = 1754,
  [SMALL_STATE(88)] = 1767,
  [SMALL_STATE(89)] = 1776,
  [SMALL_STATE(90)] = 1785,
  [SMALL_STATE(91)] = 1794,
  [SMALL_STATE(92)] = 1804,
  [SMALL_STATE(93)] = 1814,
  [SMALL_STATE(94)] = 1824,
  [SMALL_STATE(95)] = 1834,
  [SMALL_STATE(96)] = 1844,
  [SMALL_STATE(97)] = 1851,
  [SMALL_STATE(98)] = 1858,
  [SMALL_STATE(99)] = 1865,
  [SMALL_STATE(100)] = 1872,
  [SMALL_STATE(101)] = 1879,
  [SMALL_STATE(102)] = 1886,
  [SMALL_STATE(103)] = 1893,
  [SMALL_STATE(104)] = 1900,
  [SMALL_STATE(105)] = 1907,
  [SMALL_STATE(106)] = 1914,
  [SMALL_STATE(107)] = 1921,
  [SMALL_STATE(108)] = 1928,
  [SMALL_STATE(109)] = 1935,
  [SMALL_STATE(110)] = 1942,
  [SMALL_STATE(111)] = 1949,
  [SMALL_STATE(112)] = 1953,
  [SMALL_STATE(113)] = 1957,
  [SMALL_STATE(114)] = 1961,
  [SMALL_STATE(115)] = 1965,
  [SMALL_STATE(116)] = 1969,
  [SMALL_STATE(117)] = 1973,
  [SMALL_STATE(118)] = 1977,
  [SMALL_STATE(119)] = 1981,
  [SMALL_STATE(120)] = 1985,
  [SMALL_STATE(121)] = 1989,
  [SMALL_STATE(122)] = 1993,
  [SMALL_STATE(123)] = 1997,
  [SMALL_STATE(124)] = 2001,
  [SMALL_STATE(125)] = 2005,
  [SMALL_STATE(126)] = 2009,
  [SMALL_STATE(127)] = 2013,
  [SMALL_STATE(128)] = 2017,
  [SMALL_STATE(129)] = 2021,
  [SMALL_STATE(130)] = 2025,
  [SMALL_STATE(131)] = 2029,
  [SMALL_STATE(132)] = 2033,
  [SMALL_STATE(133)] = 2037,
  [SMALL_STATE(134)] = 2041,
  [SMALL_STATE(135)] = 2045,
  [SMALL_STATE(136)] = 2049,
  [SMALL_STATE(137)] = 2053,
  [SMALL_STATE(138)] = 2057,
  [SMALL_STATE(139)] = 2061,
  [SMALL_STATE(140)] = 2065,
  [SMALL_STATE(141)] = 2069,
  [SMALL_STATE(142)] = 2073,
  [SMALL_STATE(143)] = 2077,
  [SMALL_STATE(144)] = 2081,
  [SMALL_STATE(145)] = 2085,
  [SMALL_STATE(146)] = 2089,
  [SMALL_STATE(147)] = 2093,
  [SMALL_STATE(148)] = 2097,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [5] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(135),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(23),
  [13] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(42),
  [16] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(95),
  [19] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [21] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0),
  [23] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [26] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(22),
  [29] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 5, 0, 0),
  [31] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 5, 0, 0),
  [33] = {.entry = {.count = 1, .reusable = false}}, SHIFT(42),
  [35] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [37] = {.entry = {.count = 1, .reusable = false}}, SHIFT(135),
  [39] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_if_statement, 4, 0, 0),
  [41] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_if_statement, 4, 0, 0),
  [43] = {.entry = {.count = 1, .reusable = false}}, SHIFT(92),
  [45] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [47] = {.entry = {.count = 1, .reusable = true}}, SHIFT(100),
  [49] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [52] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [55] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [58] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_element_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [61] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [63] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [65] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(69),
  [68] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(92),
  [71] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(135),
  [74] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(23),
  [77] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [79] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [81] = {.entry = {.count = 1, .reusable = false}}, SHIFT(70),
  [83] = {.entry = {.count = 1, .reusable = false}}, SHIFT(21),
  [85] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [87] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(70),
  [90] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(21),
  [93] = {.entry = {.count = 1, .reusable = true}}, SHIFT(72),
  [95] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [97] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [99] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [101] = {.entry = {.count = 1, .reusable = true}}, SHIFT(138),
  [103] = {.entry = {.count = 1, .reusable = true}}, SHIFT(117),
  [105] = {.entry = {.count = 1, .reusable = true}}, SHIFT(139),
  [107] = {.entry = {.count = 1, .reusable = true}}, SHIFT(140),
  [109] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_statement, 1, 0, 0),
  [111] = {.entry = {.count = 1, .reusable = true}}, SHIFT(118),
  [113] = {.entry = {.count = 1, .reusable = true}}, SHIFT(145),
  [115] = {.entry = {.count = 1, .reusable = true}}, SHIFT(127),
  [117] = {.entry = {.count = 1, .reusable = true}}, SHIFT(146),
  [119] = {.entry = {.count = 1, .reusable = true}}, SHIFT(147),
  [121] = {.entry = {.count = 1, .reusable = true}}, SHIFT(128),
  [123] = {.entry = {.count = 1, .reusable = true}}, SHIFT(134),
  [125] = {.entry = {.count = 1, .reusable = true}}, SHIFT(137),
  [127] = {.entry = {.count = 1, .reusable = true}}, SHIFT(141),
  [129] = {.entry = {.count = 1, .reusable = true}}, SHIFT(143),
  [131] = {.entry = {.count = 1, .reusable = true}}, SHIFT(144),
  [133] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_paired_statement, 1, 0, 0),
  [135] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_paired_statement, 1, 0, 0),
  [137] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_statement, 1, 0, 0),
  [139] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_statement, 1, 0, 0),
  [141] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_elif_statement, 4, 0, 0),
  [143] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_elif_statement, 4, 0, 0),
  [145] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_unpaired_statement, 1, 0, 0),
  [147] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_unpaired_statement, 1, 0, 0),
  [149] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [151] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [153] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [155] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [157] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_statement, 3, 0, 0),
  [159] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_statement, 3, 0, 0),
  [161] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_expression, 3, 0, 0),
  [163] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_expression, 3, 0, 0),
  [165] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_expression, 1, 0, 0),
  [167] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_expression, 1, 0, 0),
  [169] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_endif_statement, 3, 0, 0),
  [171] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_endif_statement, 3, 0, 0),
  [173] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_statement, 1, 0, 0),
  [175] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_statement, 1, 0, 0),
  [177] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [179] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [181] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_else_statement, 3, 0, 0),
  [183] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_else_statement, 3, 0, 0),
  [185] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [187] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [189] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [191] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [193] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_html_comment, 2, 0, 2),
  [195] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_html_comment, 2, 0, 2),
  [197] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_content, 1, 0, 1),
  [199] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_content, 1, 0, 1),
  [201] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_statement, 4, 0, 0),
  [203] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_statement, 4, 0, 0),
  [205] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_statement, 4, 0, 0),
  [207] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 4, 0, 0),
  [209] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_extends_statement, 4, 0, 0),
  [211] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_extends_statement, 4, 0, 0),
  [213] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [215] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [217] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [219] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [221] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 1, 0, 0),
  [223] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [225] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [227] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [229] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [231] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [233] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_attribute, 3, 0, 0),
  [235] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__tag_name, 1, 0, 3),
  [237] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym__tag_name, 1, 0, 3),
  [239] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [241] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [243] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [245] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [247] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [249] = {.entry = {.count = 1, .reusable = true}}, SHIFT(99),
  [251] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [253] = {.entry = {.count = 1, .reusable = true}}, SHIFT(142),
  [255] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [257] = {.entry = {.count = 1, .reusable = true}}, SHIFT(120),
  [259] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [261] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [263] = {.entry = {.count = 1, .reusable = true}}, SHIFT(148),
  [265] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [267] = {.entry = {.count = 1, .reusable = true}}, SHIFT(112),
  [269] = {.entry = {.count = 1, .reusable = true}}, SHIFT(129),
  [271] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [273] = {.entry = {.count = 1, .reusable = true}}, SHIFT(126),
  [275] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
  [277] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [279] = {.entry = {.count = 1, .reusable = true}}, SHIFT(53),
  [281] = {.entry = {.count = 1, .reusable = false}}, SHIFT(77),
  [283] = {.entry = {.count = 1, .reusable = true}}, SHIFT(119),
  [285] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [287] = {.entry = {.count = 1, .reusable = true}}, SHIFT(36),
  [289] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [291] = {.entry = {.count = 1, .reusable = true}}, SHIFT(34),
  [293] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(60),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [305] = {.entry = {.count = 1, .reusable = true}}, SHIFT(79),
  [307] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [311] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [313] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [315] = {.entry = {.count = 1, .reusable = true}}, SHIFT(62),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(81),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [321] = {.entry = {.count = 1, .reusable = true}}, SHIFT(98),
  [323] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(35),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [331] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [335] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [337] = {.entry = {.count = 1, .reusable = true}}, SHIFT(130),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_expression, 1, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(122),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [349] = {.entry = {.count = 1, .reusable = true}}, SHIFT(124),
  [351] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [357] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(131),
  [361] = {.entry = {.count = 1, .reusable = true}}, SHIFT(132),
  [363] = {.entry = {.count = 1, .reusable = true}}, SHIFT(133),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__expression_content = 0,
  ts_external_token__statement_content = 1,
  ts_external_token__html_comment = 2,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__expression_content] = sym__expression_content,
  [ts_external_token__statement_content] = sym__statement_content,
  [ts_external_token__html_comment] = sym__html_comment,
};

static const bool ts_external_scanner_states[5][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__expression_content] = true,
    [ts_external_token__statement_content] = true,
    [ts_external_token__html_comment] = true,
  },
  [2] = {
    [ts_external_token__html_comment] = true,
  },
  [3] = {
    [ts_external_token__statement_content] = true,
  },
  [4] = {
    [ts_external_token__expression_content] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_htmlaskama_external_scanner_create(void);
void tree_sitter_htmlaskama_external_scanner_destroy(void *);
bool tree_sitter_htmlaskama_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_htmlaskama_external_scanner_serialize(void *, char *);
void tree_sitter_htmlaskama_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_htmlaskama(void) {
  static const TSLanguage language = {
    .version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_htmlaskama_external_scanner_create,
      tree_sitter_htmlaskama_external_scanner_destroy,
      tree_sitter_htmlaskama_external_scanner_scan,
      tree_sitter_htmlaskama_external_scanner_serialize,
      tree_sitter_htmlaskama_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
